### ISSUE TITLE
failed: AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'

### ISSUE THREAD

**Issue by aizest** [ThomVanL/blog-azure-chaos-engineering#1]
Could you please share the versions of your packages when you successfully run chaos tool and its Azure driver?
Especially the following packages:

- chaostoolkit
- chaostoolkit-azure
- msrestazure
- msrest
- azure-common
- azure-core

I keep getting the following python module error, and found I'm not the only one who got it when searching on Internet.
`[36m[2021-05-07 17:22:49 DEBUG] [cli:74][39m Running command 'run'
[36m[2021-05-07 17:22:49 DEBUG] [cli:78][39m Using settings file '/Users/user/.chaostoolkit/settings.yaml'
[36m[2021-05-07 17:22:49 DEBUG] [settings:26][39m The Chaos Toolkit settings file could not be found at '/Users/user/.chaostoolkit/settings.yaml'.
[36m[2021-05-07 17:22:49 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-05-07 17:22:49 DEBUG] [__init__:355][39m No controls to apply on 'loader'
[36m[2021-05-07 17:22:49 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-05-07 17:22:49 DEBUG] [caching:35][39m Cached 2 activities
[32m[2021-05-07 17:22:49 INFO] [experiment:47][39m Validating the experiment's syntax
[36m[2021-05-07 17:22:49 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-05-07 17:22:49 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-05-07 17:22:49 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-05-07 17:22:51 INFO] [experiment:96][39m Experiment looks valid
[36m[2021-05-07 17:22:51 DEBUG] [caching:42][39m Clearing activities cache
[36m[2021-05-07 17:22:51 DEBUG] [caching:25][39m Building activity cache...
[36m[2021-05-07 17:22:51 DEBUG] [caching:35][39m Cached 2 activities
[36m[2021-05-07 17:22:51 DEBUG] [configuration:54][39m Loading configuration...
[36m[2021-05-07 17:22:51 DEBUG] [secret:75][39m Loading secrets...
[36m[2021-05-07 17:22:51 DEBUG] [secret:92][39m Secrets loaded
[32m[2021-05-07 17:22:51 INFO] [run:323][39m Running experiment: What is the impact on our application chain when East US NLU App Service goes offline?
[36m[2021-05-07 17:22:51 DEBUG] [__init__:39][39m Initializing controls
[32m[2021-05-07 17:22:51 INFO] [run:342][39m Steady-state strategy: default
[32m[2021-05-07 17:22:51 INFO] [run:345][39m Rollbacks strategy: always
[36m[2021-05-07 17:22:51 DEBUG] [__init__:355][39m No controls to apply on 'experiment'
[36m[2021-05-07 17:22:51 DEBUG] [run:466][39m Running steady-state hypothesis before the method
[32m[2021-05-07 17:22:51 INFO] [hypothesis:183][39m Steady state hypothesis: Application responds
[36m[2021-05-07 17:22:51 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[36m[2021-05-07 17:22:51 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-05-07 17:22:51 INFO] [activity:161][39m Probe: we-can-request-website
[36m[2021-05-07 17:22:52 DEBUG] [activity:180][39m   => succeeded with '{'status': 200, 'headers': {'Transfer-Encoding': 'chunked', 'Content-Type': 'text/html', 'Server': 'TwistedWeb/20.3.0', 'Date': 'Fri, 07 May 2021 22:22:52 GMT'}, 'body': 'hello from Rasa NLU: 0.12.3 WMT: WMT_VERSION Build Date: BUILD_DATE'}'
[36m[2021-05-07 17:22:52 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[36m[2021-05-07 17:22:52 DEBUG] [hypothesis:211][39m allowed tolerance is 200
[32m[2021-05-07 17:22:52 INFO] [hypothesis:221][39m Steady state hypothesis is met!
[36m[2021-05-07 17:22:52 DEBUG] [__init__:355][39m No controls to apply on 'hypothesis'
[32m[2021-05-07 17:22:52 INFO] [run:553][39m Playing your experiment's method now...
[36m[2021-05-07 17:22:52 DEBUG] [__init__:355][39m No controls to apply on 'method'
[36m[2021-05-07 17:22:52 DEBUG] [__init__:355][39m No controls to apply on 'activity'
[32m[2021-05-07 17:22:52 INFO] [activity:161][39m Action: stop-app-service-region-eus
[36m[2021-05-07 17:22:52 DEBUG] [python:34][39m Activity 'stop-app-service-region-eus' loaded from '/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaosazure/webapp/actions.py'
[36m[2021-05-07 17:22:52 DEBUG] [actions:29][39m Start stop_webapp: configuration='{'azure_subscription_id': 'Sams Data Science Eng', 'azure_resource_group': 'stg-datascience-asksam', 'eus_nlu_app_service': 'stg-datascience-asksam-nlu-eus.azurewebsites.net', 'traffic_manager_endpoint': 'stg-datascience-asksam-nlu.cld.samsclub.com'}', filter='where resourceGroup=='stg-datascience-asksam' and name=='stg-datascience-asksam-nlu-eus.azurewebsites.net''
[36m[2021-05-07 17:22:52 DEBUG] [activity:235][39m Activity failed
    Traceback (most recent call last):
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaosazure/webapp/actions.py", line 33, in stop_webapp
        choice = __fetch_webapp_at_random(filter, configuration, secrets)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaosazure/webapp/actions.py", line 134, in __fetch_webapp_at_random
        webapps = fetch_webapps(filter, configuration, secrets)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaosazure/webapp/actions.py", line 119, in fetch_webapps
        webapps = fetch_resources(filter, RES_TYPE_WEBAPP, secrets, configuration)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaosazure/common/resources/graph.py", line 23, in fetch_resources
        resources = client.resources(_query_request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/mgmt/resourcegraph/operations/_resource_graph_client_operations.py", line 67, in resources
        pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
        return first_node.send(pipeline_request)  # type: ignore
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
        response = self.next.send(request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
        response = self.next.send(request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
        response = self.next.send(request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
        response = self.next.send(request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
        response = self.next.send(request)
      [Previous line repeated 1 more time]
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
        response = self.next.send(request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
        response = self.next.send(request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
        _await_result(self._policy.on_request, request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_tools.py", line 29, in await_result
        result = func(*args, **kwargs)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 93, in on_request
        self._token = self._credential.get_token(*self._scopes)
    AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaoslib/activity.py", line 228, in run_activity
        result = run_python_activity(activity, configuration, secrets)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaoslib/provider/python.py", line 57, in run_python_activity
        raise ActivityFailed(
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaosazure/webapp/actions.py", line 33, in stop_webapp
        choice = __fetch_webapp_at_random(filter, configuration, secrets)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaosazure/webapp/actions.py", line 134, in __fetch_webapp_at_random
        webapps = fetch_webapps(filter, configuration, secrets)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaosazure/webapp/actions.py", line 119, in fetch_webapps
        webapps = fetch_resources(filter, RES_TYPE_WEBAPP, secrets, configuration)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/chaosazure/common/resources/graph.py", line 23, in fetch_resources
        resources = client.resources(_query_request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/mgmt/resourcegraph/operations/_resource_graph_client_operations.py", line 67, in resources
        pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 211, in run
        return first_node.send(pipeline_request)  # type: ignore
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
        response = self.next.send(request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/mgmt/core/policies/_base.py", line 47, in send
        response = self.next.send(request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
        response = self.next.send(request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
        response = self.next.send(request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 71, in send
        response = self.next.send(request)
      [Previous line repeated 1 more time]
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
        response = self.next.send(request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
        response = self.next.send(request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_base.py", line 69, in send
        _await_result(self._policy.on_request, request)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/_tools.py", line 29, in await_result
        result = func(*args, **kwargs)
      File "/Users/user/.conda/envs/chaostoolkit/lib/python3.8/site-packages/azure/core/pipeline/policies/_authentication.py", line 93, in on_request
        self._token = self._credential.get_token(*self._scopes)
    chaoslib.exceptions.ActivityFailed: AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'
[31m[2021-05-07 17:22:52 ERROR] [activity:188][39m   => failed: AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'`

**Comment by ThomVanL** [comment]
Hey there,

At the time of writing I was using:

- chaostoolkit==1.6.0
- chaostoolkit-reporting==0.13.0
- chaostoolkit-azure==0.8.3

I can't say for certain what version the other packages (msrestazure, msrest, azure-common, azure-core) were using. I also can't seem to find it in the commit history over at [chaostoolkit-incubator/chaostoolkit-azure](https://github.com/chaostoolkit-incubator/chaostoolkit-azure).

There was, at the time of writing, also a bug with the ```WebSiteManagementClient ``` and so I had to perform some additional patching in order to get things to work properly. This is also reflected in the sample's VS Code DevContainer [Dockerfile](https://github.com/ThomVanL/blog-azure-chaos-engineering/blob/main/.devcontainer/Dockerfile):

```dockerfile
RUN python3 -m venv $VIRTUAL_ENV
RUN bin/bash -c "source $VIRTUAL_ENV/bin/activate && pip3 install --no-cache-dir -U 'chaostoolkit==1.6.0' 'chaostoolkit-reporting==0.13.0' 'chaostoolkit-azure==0.8.3'"

# Temporary fix until https://github.com/chaostoolkit-incubator/chaostoolkit-azure/pull/119 is merged.
RUN git clone -b webapp_init_client_mangement https://github.com/ThomVanL/chaostoolkit-azure.git
RUN rm -rf $VIRTUAL_ENV/lib/python3.6/site-packages/chaosazure && \
    mv chaostoolkit-azure/chaosazure $VIRTUAL_ENV/lib/python3.6/site-packages && \
    rm -rf  chaostoolkit-azure
```

I think the SPN issue may have been addressed with chaostoolkit-incubator/chaostoolkit-azure#130. As soon as I have some spare time on my hands and that PR gets merged, I'll see if I can get my sample to work with a newer version of chaostoolkit-azure.

**Comment by aizest** [comment]
Thanks! These are helpful!
